name: linter-check

on: push
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v7
      - name: Install flake8
        run: pip install flake8
      - run: make lint